[package]
name = "otobusum-anlik-status"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
reqwest = "0.12.12"
serenity = "0.12.4"
tokio = { version = "1.43.0", features = ["macros", "rt"] }
